name: ZAP Security Scan

on: [push] # Each time you make a 'git push' on repo, test start automatically

permissions:
  contents: read
  issues: write # Required to allow ZAP to create the Issue in your repo

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Exec a ZAP scan
    steps:
      - name: Exec ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://juice-shop.herokuapp.com/'
          
      - name: Debug - List generated files
        run: ls -la

      - name: Load repost as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-results
          # ZAP action save default report as report_html.html
          path: | 
            report_html.html
            report_md.md
            report_json.json